"""add cart item model

Revision ID: 3fb8ce3ff7c8
Revises: 4c8ebd4e9558
Create Date: 2025-05-26 15:21:49.212554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fb8ce3ff7c8'
down_revision = '4c8ebd4e9558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('cart_items_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('cart_items_ibfk_2', type_='foreignkey')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.create_foreign_key('cart_items_ibfk_2', 'product', ['product_id'], ['id'])
        batch_op.create_foreign_key('cart_items_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
