"""corrige CartItem com ForeignKey

Revision ID: 731ac8c3d5cd
Revises: 3fb8ce3ff7c8
Create Date: 2025-05-27 15:58:34.573456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731ac8c3d5cd'
down_revision = '3fb8ce3ff7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
